apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
  namespace: ml
  labels:
    model-version: "fd6981f"
spec:
  predictor:
    serviceAccountName: sa-s3-access
    sklearn:
      storageUri: s3://mlops123-299029453147-us-east-1-an/models/churn_model-fd6981f.pkl
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"