apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
  namespace: ml
  labels:
    model-version: "4315156"
spec:
  predictor:
    serviceAccountName: sa-s3-access
    sklearn:
      storageUri: s3://ml-s3-272558305029-us-east-1-an/models/churn_model-4315156.pkl
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
